import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { ethers } from "ethers";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [currentAccount, setCurrentAccount] = useState("");
  
  const checkIfWalletConnected = async () => {
    try {
      console.log("Checking wallet")
      const { ethereum } = window;


      if (!ethereum) {
        console.log("Make sure you have metamask!");
      } else {
        console.log("We have the ethereum object", ethereum);
        getAllWaves();
        getAllStations();
      }

      /*
     * Check if we're authorized to access the user's wallet
     */
      const accounts = await ethereum.request({ method: "eth_accounts" })
      console.log(accounts)

      if (accounts.length != 0) {
        const account = accounts[0];
        setCurrentAccount(account)
        console.log("Found an authorized account:", account);
      } else {
        console.log("No authorized account found")
      }

    } catch (error) {
      console.log(error)
    }
  }

  const connectWallet = async () => {
    try {

      const { ethereum } = window;

      if (!ethereum) {
        alert("Get MetaMask!");
        return;
      }

      const accounts = await ethereum.request({ method: "eth_requestAccounts" });

      console.log("Connected", accounts[0]);
      setCurrentAccount(accounts[0]);

    } catch (error) {
      console.log(error)
    }
  }

  useEffect(() => {
    checkIfWalletConnected()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>This is rinkeby radio station</h2>

      <Link href="/stayFocus">
        <a>Stay Focus</a>
      </Link>

      <Link href="/somethingToSomeone">
        <a>Something To Someone</a>
      </Link>
      
      <div>
        <Link href="/authTest">
         <a>Auth Test</a>
        </Link>
      </div>

      <div>
        A little support?
      </div>


      {(currentAccount == "") ?
        <button className="waveButton" onClick={connectWallet}>
          Connect Wallet
        </button> : <></>
      }
    </div>
  )
}
